resources:
  repositories:
  - repository: pipelines_repo
    type: github
    endpoint: ROCm
    name: ROCm/ROCm

variables:
- group: common
- template: /.azuredevops/variables-global.yml@pipelines_repo

trigger:
  batch: true
  branches:
    include:
    - amd-staging
    - amd-mainline
  paths:
    exclude:
    - .github
    - ISSUE_TEMPLATE
    - '*.md'
    - CODEOWNERS
    - LICENSE

pr:
  autoCancel: true
  branches:
    include:
    - amd-staging
    - amd-mainline
  paths:
    exclude:
    - .github
    - ISSUE_TEMPLATE
    - '*.md'
    - CODEOWNERS
    - LICENSE
  drafts: false

jobs:
  - template: ${{ variables.CI_COMPONENT_PATH }}/rocprofiler-sdk.yml@pipelines_repo
